// automatically generated by the FlatBuffers compiler, do not modify

package bpio;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ConfigurationResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ConfigurationResponse getRootAsConfigurationResponse(ByteBuffer _bb) { return getRootAsConfigurationResponse(_bb, new ConfigurationResponse()); }
  public static ConfigurationResponse getRootAsConfigurationResponse(ByteBuffer _bb, ConfigurationResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ConfigurationResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String error() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer errorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createConfigurationResponse(FlatBufferBuilder builder,
      int errorOffset) {
    builder.startTable(1);
    ConfigurationResponse.addError(builder, errorOffset);
    return ConfigurationResponse.endConfigurationResponse(builder);
  }

  public static void startConfigurationResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addError(FlatBufferBuilder builder, int errorOffset) { builder.addOffset(0, errorOffset, 0); }
  public static int endConfigurationResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ConfigurationResponse get(int j) { return get(new ConfigurationResponse(), j); }
    public ConfigurationResponse get(ConfigurationResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

