// automatically generated by the FlatBuffers compiler, do not modify

package bpio;

@SuppressWarnings("unused")
public final class RequestPacketContents {
  private RequestPacketContents() { }
  public static final byte NONE = 0;
  public static final byte Monster = 1;
  public static final byte StatusRequest = 2;
  public static final byte ConfigurationRequest = 3;
  public static final byte DataRequest = 4;

  public static final String[] names = { "NONE", "Monster", "StatusRequest", "ConfigurationRequest", "DataRequest", };

  public static String name(int e) { return names[e]; }
}

