// automatically generated by the FlatBuffers compiler, do not modify

package bpio;

@SuppressWarnings("unused")
public final class ResponsePacketContents {
  private ResponsePacketContents() { }
  public static final byte NONE = 0;
  public static final byte StatusResponse = 1;
  public static final byte ConfigurationResponse = 2;
  public static final byte DataResponse = 3;

  public static final String[] names = { "NONE", "StatusResponse", "ConfigurationResponse", "DataResponse", };

  public static String name(int e) { return names[e]; }
}

