// automatically generated by the FlatBuffers compiler, do not modify

package bpio;

@SuppressWarnings("unused")
public final class StatusRequestTypes {
  private StatusRequestTypes() { }
  public static final byte All = 0;
  public static final byte Version = 1;
  public static final byte Mode = 2;
  public static final byte Pullup = 3;
  public static final byte PSU = 4;
  public static final byte ADC = 5;
  public static final byte IO = 6;
  public static final byte Disk = 7;
  public static final byte LED = 8;

  public static final String[] names = { "All", "Version", "Mode", "Pullup", "PSU", "ADC", "IO", "Disk", "LED", };

  public static String name(int e) { return names[e]; }
}

