// automatically generated by the FlatBuffers compiler, do not modify

package bpio;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class StatusRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static StatusRequest getRootAsStatusRequest(ByteBuffer _bb) { return getRootAsStatusRequest(_bb, new StatusRequest()); }
  public static StatusRequest getRootAsStatusRequest(ByteBuffer _bb, StatusRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StatusRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte query(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int queryLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector queryVector() { return queryVector(new ByteVector()); }
  public ByteVector queryVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer queryAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer queryInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createStatusRequest(FlatBufferBuilder builder,
      int queryOffset) {
    builder.startTable(1);
    StatusRequest.addQuery(builder, queryOffset);
    return StatusRequest.endStatusRequest(builder);
  }

  public static void startStatusRequest(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addQuery(FlatBufferBuilder builder, int queryOffset) { builder.addOffset(0, queryOffset, 0); }
  public static int createQueryVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createQueryVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startQueryVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endStatusRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StatusRequest get(int j) { return get(new StatusRequest(), j); }
    public StatusRequest get(StatusRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

