// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library bpio;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;


enum StatusRequestTypes {
  All(0),
  Version(1),
  Mode(2),
  Pullup(3),
  PSU(4),
  ADC(5),
  IO(6),
  Disk(7),
  LED(8);

  final int value;
  const StatusRequestTypes(this.value);

  factory StatusRequestTypes.fromValue(int value) {
    switch (value) {
      case 0: return StatusRequestTypes.All;
      case 1: return StatusRequestTypes.Version;
      case 2: return StatusRequestTypes.Mode;
      case 3: return StatusRequestTypes.Pullup;
      case 4: return StatusRequestTypes.PSU;
      case 5: return StatusRequestTypes.ADC;
      case 6: return StatusRequestTypes.IO;
      case 7: return StatusRequestTypes.Disk;
      case 8: return StatusRequestTypes.LED;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static StatusRequestTypes? _createOrNull(int? value) =>
      value == null ? null : StatusRequestTypes.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 8;
  static const fb.Reader<StatusRequestTypes> reader = _StatusRequestTypesReader();
}

class _StatusRequestTypesReader extends fb.Reader<StatusRequestTypes> {
  const _StatusRequestTypesReader();

  @override
  int get size => 1;

  @override
  StatusRequestTypes read(fb.BufferContext bc, int offset) =>
      StatusRequestTypes.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum RequestPacketContentsTypeId {
  NONE(0),
  StatusRequest(1),
  ConfigurationRequest(2),
  DataRequest(3);

  final int value;
  const RequestPacketContentsTypeId(this.value);

  factory RequestPacketContentsTypeId.fromValue(int value) {
    switch (value) {
      case 0: return RequestPacketContentsTypeId.NONE;
      case 1: return RequestPacketContentsTypeId.StatusRequest;
      case 2: return RequestPacketContentsTypeId.ConfigurationRequest;
      case 3: return RequestPacketContentsTypeId.DataRequest;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static RequestPacketContentsTypeId? _createOrNull(int? value) =>
      value == null ? null : RequestPacketContentsTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 3;
  static const fb.Reader<RequestPacketContentsTypeId> reader = _RequestPacketContentsTypeIdReader();
}

class _RequestPacketContentsTypeIdReader extends fb.Reader<RequestPacketContentsTypeId> {
  const _RequestPacketContentsTypeIdReader();

  @override
  int get size => 1;

  @override
  RequestPacketContentsTypeId read(fb.BufferContext bc, int offset) =>
      RequestPacketContentsTypeId.fromValue(const fb.Uint8Reader().read(bc, offset));
}

enum ResponsePacketContentsTypeId {
  NONE(0),
  ErrorResponse(1),
  StatusResponse(2),
  ConfigurationResponse(3),
  DataResponse(4);

  final int value;
  const ResponsePacketContentsTypeId(this.value);

  factory ResponsePacketContentsTypeId.fromValue(int value) {
    switch (value) {
      case 0: return ResponsePacketContentsTypeId.NONE;
      case 1: return ResponsePacketContentsTypeId.ErrorResponse;
      case 2: return ResponsePacketContentsTypeId.StatusResponse;
      case 3: return ResponsePacketContentsTypeId.ConfigurationResponse;
      case 4: return ResponsePacketContentsTypeId.DataResponse;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static ResponsePacketContentsTypeId? _createOrNull(int? value) =>
      value == null ? null : ResponsePacketContentsTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 4;
  static const fb.Reader<ResponsePacketContentsTypeId> reader = _ResponsePacketContentsTypeIdReader();
}

class _ResponsePacketContentsTypeIdReader extends fb.Reader<ResponsePacketContentsTypeId> {
  const _ResponsePacketContentsTypeIdReader();

  @override
  int get size => 1;

  @override
  ResponsePacketContentsTypeId read(fb.BufferContext bc, int offset) =>
      ResponsePacketContentsTypeId.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class StatusRequest {
  StatusRequest._(this._bc, this._bcOffset);
  factory StatusRequest(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StatusRequest> reader = _StatusRequestReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<StatusRequestTypes>? get query => const fb.ListReader<StatusRequestTypes>(StatusRequestTypes.reader).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'StatusRequest{query: ${query}}';
  }
}

class _StatusRequestReader extends fb.TableReader<StatusRequest> {
  const _StatusRequestReader();

  @override
  StatusRequest createObject(fb.BufferContext bc, int offset) => 
    StatusRequest._(bc, offset);
}

class StatusRequestBuilder {
  StatusRequestBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addQueryOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StatusRequestObjectBuilder extends fb.ObjectBuilder {
  final List<StatusRequestTypes>? _query;

  StatusRequestObjectBuilder({
    List<StatusRequestTypes>? query,
  })
      : _query = query;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? queryOffset = _query == null ? null
        : fbBuilder.writeListInt8(_query!.map((f) => f.value).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, queryOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class StatusResponse {
  StatusResponse._(this._bc, this._bcOffset);
  factory StatusResponse(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StatusResponse> reader = _StatusResponseReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get error => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  int get hardwareVersionMajor => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 6, 0);
  int get hardwareVersionMinor => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 8, 0);
  int get firmwareVersionMajor => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 10, 0);
  int get firmwareVersionMinor => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 12, 0);
  String? get firmwareGitHash => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 14);
  String? get firmwareDate => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 16);
  List<String>? get modesAvailable => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 18);
  String? get modeCurrent => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 20);
  List<String>? get modePinLabels => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 22);
  bool get modeBitorderMsb => const fb.BoolReader().vTableGet(_bc, _bcOffset, 24, false);
  bool get psuEnabled => const fb.BoolReader().vTableGet(_bc, _bcOffset, 26, false);
  int get psuSetMv => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 28, 0);
  int get psuSetMa => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 30, 0);
  int get psuMeasuredMv => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 32, 0);
  int get psuMeasuredMa => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 34, 0);
  bool get psuCurrentError => const fb.BoolReader().vTableGet(_bc, _bcOffset, 36, false);
  bool get pullupEnabled => const fb.BoolReader().vTableGet(_bc, _bcOffset, 38, false);
  int get pullxConfig => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 40, 0);
  List<int>? get adcMv => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 42);
  int get ioDirection => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 44, 0);
  int get ioValue => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 46, 0);
  double get diskSizeMb => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 48, 0.0);
  double get diskUsedMb => const fb.Float32Reader().vTableGet(_bc, _bcOffset, 50, 0.0);
  int get ledCount => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 52, 0);

  @override
  String toString() {
    return 'StatusResponse{error: ${error}, hardwareVersionMajor: ${hardwareVersionMajor}, hardwareVersionMinor: ${hardwareVersionMinor}, firmwareVersionMajor: ${firmwareVersionMajor}, firmwareVersionMinor: ${firmwareVersionMinor}, firmwareGitHash: ${firmwareGitHash}, firmwareDate: ${firmwareDate}, modesAvailable: ${modesAvailable}, modeCurrent: ${modeCurrent}, modePinLabels: ${modePinLabels}, modeBitorderMsb: ${modeBitorderMsb}, psuEnabled: ${psuEnabled}, psuSetMv: ${psuSetMv}, psuSetMa: ${psuSetMa}, psuMeasuredMv: ${psuMeasuredMv}, psuMeasuredMa: ${psuMeasuredMa}, psuCurrentError: ${psuCurrentError}, pullupEnabled: ${pullupEnabled}, pullxConfig: ${pullxConfig}, adcMv: ${adcMv}, ioDirection: ${ioDirection}, ioValue: ${ioValue}, diskSizeMb: ${diskSizeMb}, diskUsedMb: ${diskUsedMb}, ledCount: ${ledCount}}';
  }
}

class _StatusResponseReader extends fb.TableReader<StatusResponse> {
  const _StatusResponseReader();

  @override
  StatusResponse createObject(fb.BufferContext bc, int offset) => 
    StatusResponse._(bc, offset);
}

class StatusResponseBuilder {
  StatusResponseBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(25);
  }

  int addErrorOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addHardwareVersionMajor(int? hardwareVersionMajor) {
    fbBuilder.addUint8(1, hardwareVersionMajor);
    return fbBuilder.offset;
  }
  int addHardwareVersionMinor(int? hardwareVersionMinor) {
    fbBuilder.addUint8(2, hardwareVersionMinor);
    return fbBuilder.offset;
  }
  int addFirmwareVersionMajor(int? firmwareVersionMajor) {
    fbBuilder.addUint8(3, firmwareVersionMajor);
    return fbBuilder.offset;
  }
  int addFirmwareVersionMinor(int? firmwareVersionMinor) {
    fbBuilder.addUint8(4, firmwareVersionMinor);
    return fbBuilder.offset;
  }
  int addFirmwareGitHashOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addFirmwareDateOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addModesAvailableOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addModeCurrentOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }
  int addModePinLabelsOffset(int? offset) {
    fbBuilder.addOffset(9, offset);
    return fbBuilder.offset;
  }
  int addModeBitorderMsb(bool? modeBitorderMsb) {
    fbBuilder.addBool(10, modeBitorderMsb);
    return fbBuilder.offset;
  }
  int addPsuEnabled(bool? psuEnabled) {
    fbBuilder.addBool(11, psuEnabled);
    return fbBuilder.offset;
  }
  int addPsuSetMv(int? psuSetMv) {
    fbBuilder.addUint32(12, psuSetMv);
    return fbBuilder.offset;
  }
  int addPsuSetMa(int? psuSetMa) {
    fbBuilder.addUint32(13, psuSetMa);
    return fbBuilder.offset;
  }
  int addPsuMeasuredMv(int? psuMeasuredMv) {
    fbBuilder.addUint32(14, psuMeasuredMv);
    return fbBuilder.offset;
  }
  int addPsuMeasuredMa(int? psuMeasuredMa) {
    fbBuilder.addUint32(15, psuMeasuredMa);
    return fbBuilder.offset;
  }
  int addPsuCurrentError(bool? psuCurrentError) {
    fbBuilder.addBool(16, psuCurrentError);
    return fbBuilder.offset;
  }
  int addPullupEnabled(bool? pullupEnabled) {
    fbBuilder.addBool(17, pullupEnabled);
    return fbBuilder.offset;
  }
  int addPullxConfig(int? pullxConfig) {
    fbBuilder.addUint32(18, pullxConfig);
    return fbBuilder.offset;
  }
  int addAdcMvOffset(int? offset) {
    fbBuilder.addOffset(19, offset);
    return fbBuilder.offset;
  }
  int addIoDirection(int? ioDirection) {
    fbBuilder.addUint8(20, ioDirection);
    return fbBuilder.offset;
  }
  int addIoValue(int? ioValue) {
    fbBuilder.addUint8(21, ioValue);
    return fbBuilder.offset;
  }
  int addDiskSizeMb(double? diskSizeMb) {
    fbBuilder.addFloat32(22, diskSizeMb);
    return fbBuilder.offset;
  }
  int addDiskUsedMb(double? diskUsedMb) {
    fbBuilder.addFloat32(23, diskUsedMb);
    return fbBuilder.offset;
  }
  int addLedCount(int? ledCount) {
    fbBuilder.addUint8(24, ledCount);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StatusResponseObjectBuilder extends fb.ObjectBuilder {
  final String? _error;
  final int? _hardwareVersionMajor;
  final int? _hardwareVersionMinor;
  final int? _firmwareVersionMajor;
  final int? _firmwareVersionMinor;
  final String? _firmwareGitHash;
  final String? _firmwareDate;
  final List<String>? _modesAvailable;
  final String? _modeCurrent;
  final List<String>? _modePinLabels;
  final bool? _modeBitorderMsb;
  final bool? _psuEnabled;
  final int? _psuSetMv;
  final int? _psuSetMa;
  final int? _psuMeasuredMv;
  final int? _psuMeasuredMa;
  final bool? _psuCurrentError;
  final bool? _pullupEnabled;
  final int? _pullxConfig;
  final List<int>? _adcMv;
  final int? _ioDirection;
  final int? _ioValue;
  final double? _diskSizeMb;
  final double? _diskUsedMb;
  final int? _ledCount;

  StatusResponseObjectBuilder({
    String? error,
    int? hardwareVersionMajor,
    int? hardwareVersionMinor,
    int? firmwareVersionMajor,
    int? firmwareVersionMinor,
    String? firmwareGitHash,
    String? firmwareDate,
    List<String>? modesAvailable,
    String? modeCurrent,
    List<String>? modePinLabels,
    bool? modeBitorderMsb,
    bool? psuEnabled,
    int? psuSetMv,
    int? psuSetMa,
    int? psuMeasuredMv,
    int? psuMeasuredMa,
    bool? psuCurrentError,
    bool? pullupEnabled,
    int? pullxConfig,
    List<int>? adcMv,
    int? ioDirection,
    int? ioValue,
    double? diskSizeMb,
    double? diskUsedMb,
    int? ledCount,
  })
      : _error = error,
        _hardwareVersionMajor = hardwareVersionMajor,
        _hardwareVersionMinor = hardwareVersionMinor,
        _firmwareVersionMajor = firmwareVersionMajor,
        _firmwareVersionMinor = firmwareVersionMinor,
        _firmwareGitHash = firmwareGitHash,
        _firmwareDate = firmwareDate,
        _modesAvailable = modesAvailable,
        _modeCurrent = modeCurrent,
        _modePinLabels = modePinLabels,
        _modeBitorderMsb = modeBitorderMsb,
        _psuEnabled = psuEnabled,
        _psuSetMv = psuSetMv,
        _psuSetMa = psuSetMa,
        _psuMeasuredMv = psuMeasuredMv,
        _psuMeasuredMa = psuMeasuredMa,
        _psuCurrentError = psuCurrentError,
        _pullupEnabled = pullupEnabled,
        _pullxConfig = pullxConfig,
        _adcMv = adcMv,
        _ioDirection = ioDirection,
        _ioValue = ioValue,
        _diskSizeMb = diskSizeMb,
        _diskUsedMb = diskUsedMb,
        _ledCount = ledCount;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? errorOffset = _error == null ? null
        : fbBuilder.writeString(_error!);
    final int? firmwareGitHashOffset = _firmwareGitHash == null ? null
        : fbBuilder.writeString(_firmwareGitHash!);
    final int? firmwareDateOffset = _firmwareDate == null ? null
        : fbBuilder.writeString(_firmwareDate!);
    final int? modesAvailableOffset = _modesAvailable == null ? null
        : fbBuilder.writeList(_modesAvailable!.map(fbBuilder.writeString).toList());
    final int? modeCurrentOffset = _modeCurrent == null ? null
        : fbBuilder.writeString(_modeCurrent!);
    final int? modePinLabelsOffset = _modePinLabels == null ? null
        : fbBuilder.writeList(_modePinLabels!.map(fbBuilder.writeString).toList());
    final int? adcMvOffset = _adcMv == null ? null
        : fbBuilder.writeListUint32(_adcMv!);
    fbBuilder.startTable(25);
    fbBuilder.addOffset(0, errorOffset);
    fbBuilder.addUint8(1, _hardwareVersionMajor);
    fbBuilder.addUint8(2, _hardwareVersionMinor);
    fbBuilder.addUint8(3, _firmwareVersionMajor);
    fbBuilder.addUint8(4, _firmwareVersionMinor);
    fbBuilder.addOffset(5, firmwareGitHashOffset);
    fbBuilder.addOffset(6, firmwareDateOffset);
    fbBuilder.addOffset(7, modesAvailableOffset);
    fbBuilder.addOffset(8, modeCurrentOffset);
    fbBuilder.addOffset(9, modePinLabelsOffset);
    fbBuilder.addBool(10, _modeBitorderMsb);
    fbBuilder.addBool(11, _psuEnabled);
    fbBuilder.addUint32(12, _psuSetMv);
    fbBuilder.addUint32(13, _psuSetMa);
    fbBuilder.addUint32(14, _psuMeasuredMv);
    fbBuilder.addUint32(15, _psuMeasuredMa);
    fbBuilder.addBool(16, _psuCurrentError);
    fbBuilder.addBool(17, _pullupEnabled);
    fbBuilder.addUint32(18, _pullxConfig);
    fbBuilder.addOffset(19, adcMvOffset);
    fbBuilder.addUint8(20, _ioDirection);
    fbBuilder.addUint8(21, _ioValue);
    fbBuilder.addFloat32(22, _diskSizeMb);
    fbBuilder.addFloat32(23, _diskUsedMb);
    fbBuilder.addUint8(24, _ledCount);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ModeConfiguration {
  ModeConfiguration._(this._bc, this._bcOffset);
  factory ModeConfiguration(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ModeConfiguration> reader = _ModeConfigurationReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get speed => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 20000);
  int get dataBits => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 6, 8);
  bool get parity => const fb.BoolReader().vTableGet(_bc, _bcOffset, 8, false);
  int get stopBits => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 10, 1);
  bool get flowControl => const fb.BoolReader().vTableGet(_bc, _bcOffset, 12, false);
  bool get signalInversion => const fb.BoolReader().vTableGet(_bc, _bcOffset, 14, false);
  bool get clockStretch => const fb.BoolReader().vTableGet(_bc, _bcOffset, 16, false);
  bool get clockPolarity => const fb.BoolReader().vTableGet(_bc, _bcOffset, 18, false);
  bool get clockPhase => const fb.BoolReader().vTableGet(_bc, _bcOffset, 20, false);
  bool get chipSelectIdle => const fb.BoolReader().vTableGet(_bc, _bcOffset, 22, true);
  int get submode => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 24, 0);
  int get txModulation => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 26, 0);
  int get rxSensor => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 28, 0);

  @override
  String toString() {
    return 'ModeConfiguration{speed: ${speed}, dataBits: ${dataBits}, parity: ${parity}, stopBits: ${stopBits}, flowControl: ${flowControl}, signalInversion: ${signalInversion}, clockStretch: ${clockStretch}, clockPolarity: ${clockPolarity}, clockPhase: ${clockPhase}, chipSelectIdle: ${chipSelectIdle}, submode: ${submode}, txModulation: ${txModulation}, rxSensor: ${rxSensor}}';
  }
}

class _ModeConfigurationReader extends fb.TableReader<ModeConfiguration> {
  const _ModeConfigurationReader();

  @override
  ModeConfiguration createObject(fb.BufferContext bc, int offset) => 
    ModeConfiguration._(bc, offset);
}

class ModeConfigurationBuilder {
  ModeConfigurationBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(13);
  }

  int addSpeed(int? speed) {
    fbBuilder.addUint32(0, speed);
    return fbBuilder.offset;
  }
  int addDataBits(int? dataBits) {
    fbBuilder.addUint8(1, dataBits);
    return fbBuilder.offset;
  }
  int addParity(bool? parity) {
    fbBuilder.addBool(2, parity);
    return fbBuilder.offset;
  }
  int addStopBits(int? stopBits) {
    fbBuilder.addUint8(3, stopBits);
    return fbBuilder.offset;
  }
  int addFlowControl(bool? flowControl) {
    fbBuilder.addBool(4, flowControl);
    return fbBuilder.offset;
  }
  int addSignalInversion(bool? signalInversion) {
    fbBuilder.addBool(5, signalInversion);
    return fbBuilder.offset;
  }
  int addClockStretch(bool? clockStretch) {
    fbBuilder.addBool(6, clockStretch);
    return fbBuilder.offset;
  }
  int addClockPolarity(bool? clockPolarity) {
    fbBuilder.addBool(7, clockPolarity);
    return fbBuilder.offset;
  }
  int addClockPhase(bool? clockPhase) {
    fbBuilder.addBool(8, clockPhase);
    return fbBuilder.offset;
  }
  int addChipSelectIdle(bool? chipSelectIdle) {
    fbBuilder.addBool(9, chipSelectIdle);
    return fbBuilder.offset;
  }
  int addSubmode(int? submode) {
    fbBuilder.addUint8(10, submode);
    return fbBuilder.offset;
  }
  int addTxModulation(int? txModulation) {
    fbBuilder.addUint32(11, txModulation);
    return fbBuilder.offset;
  }
  int addRxSensor(int? rxSensor) {
    fbBuilder.addUint8(12, rxSensor);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ModeConfigurationObjectBuilder extends fb.ObjectBuilder {
  final int? _speed;
  final int? _dataBits;
  final bool? _parity;
  final int? _stopBits;
  final bool? _flowControl;
  final bool? _signalInversion;
  final bool? _clockStretch;
  final bool? _clockPolarity;
  final bool? _clockPhase;
  final bool? _chipSelectIdle;
  final int? _submode;
  final int? _txModulation;
  final int? _rxSensor;

  ModeConfigurationObjectBuilder({
    int? speed,
    int? dataBits,
    bool? parity,
    int? stopBits,
    bool? flowControl,
    bool? signalInversion,
    bool? clockStretch,
    bool? clockPolarity,
    bool? clockPhase,
    bool? chipSelectIdle,
    int? submode,
    int? txModulation,
    int? rxSensor,
  })
      : _speed = speed,
        _dataBits = dataBits,
        _parity = parity,
        _stopBits = stopBits,
        _flowControl = flowControl,
        _signalInversion = signalInversion,
        _clockStretch = clockStretch,
        _clockPolarity = clockPolarity,
        _clockPhase = clockPhase,
        _chipSelectIdle = chipSelectIdle,
        _submode = submode,
        _txModulation = txModulation,
        _rxSensor = rxSensor;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(13);
    fbBuilder.addUint32(0, _speed);
    fbBuilder.addUint8(1, _dataBits);
    fbBuilder.addBool(2, _parity);
    fbBuilder.addUint8(3, _stopBits);
    fbBuilder.addBool(4, _flowControl);
    fbBuilder.addBool(5, _signalInversion);
    fbBuilder.addBool(6, _clockStretch);
    fbBuilder.addBool(7, _clockPolarity);
    fbBuilder.addBool(8, _clockPhase);
    fbBuilder.addBool(9, _chipSelectIdle);
    fbBuilder.addUint8(10, _submode);
    fbBuilder.addUint32(11, _txModulation);
    fbBuilder.addUint8(12, _rxSensor);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ConfigurationRequest {
  ConfigurationRequest._(this._bc, this._bcOffset);
  factory ConfigurationRequest(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ConfigurationRequest> reader = _ConfigurationRequestReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get mode => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  ModeConfiguration? get modeConfiguration => ModeConfiguration.reader.vTableGetNullable(_bc, _bcOffset, 6);
  bool get modeBitorderMsb => const fb.BoolReader().vTableGet(_bc, _bcOffset, 8, false);
  bool get modeBitorderLsb => const fb.BoolReader().vTableGet(_bc, _bcOffset, 10, false);
  bool get psuDisable => const fb.BoolReader().vTableGet(_bc, _bcOffset, 12, false);
  bool get psuEnable => const fb.BoolReader().vTableGet(_bc, _bcOffset, 14, false);
  int get psuSetMv => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 16, 0);
  int get psuSetMa => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 18, 300);
  bool get pullupDisable => const fb.BoolReader().vTableGet(_bc, _bcOffset, 20, false);
  bool get pullupEnable => const fb.BoolReader().vTableGet(_bc, _bcOffset, 22, false);
  int get pullxConfig => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 24, 0);
  int get ioDirectionMask => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 26, 0);
  int get ioDirection => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 28, 0);
  int get ioValueMask => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 30, 0);
  int get ioValue => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 32, 0);
  bool get ledResume => const fb.BoolReader().vTableGet(_bc, _bcOffset, 34, false);
  List<int>? get ledColor => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 36);
  String? get printString => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 38);
  bool get hardwareBootloader => const fb.BoolReader().vTableGet(_bc, _bcOffset, 40, false);
  bool get hardwareReset => const fb.BoolReader().vTableGet(_bc, _bcOffset, 42, false);

  @override
  String toString() {
    return 'ConfigurationRequest{mode: ${mode}, modeConfiguration: ${modeConfiguration}, modeBitorderMsb: ${modeBitorderMsb}, modeBitorderLsb: ${modeBitorderLsb}, psuDisable: ${psuDisable}, psuEnable: ${psuEnable}, psuSetMv: ${psuSetMv}, psuSetMa: ${psuSetMa}, pullupDisable: ${pullupDisable}, pullupEnable: ${pullupEnable}, pullxConfig: ${pullxConfig}, ioDirectionMask: ${ioDirectionMask}, ioDirection: ${ioDirection}, ioValueMask: ${ioValueMask}, ioValue: ${ioValue}, ledResume: ${ledResume}, ledColor: ${ledColor}, printString: ${printString}, hardwareBootloader: ${hardwareBootloader}, hardwareReset: ${hardwareReset}}';
  }
}

class _ConfigurationRequestReader extends fb.TableReader<ConfigurationRequest> {
  const _ConfigurationRequestReader();

  @override
  ConfigurationRequest createObject(fb.BufferContext bc, int offset) => 
    ConfigurationRequest._(bc, offset);
}

class ConfigurationRequestBuilder {
  ConfigurationRequestBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(20);
  }

  int addModeOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addModeConfigurationOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addModeBitorderMsb(bool? modeBitorderMsb) {
    fbBuilder.addBool(2, modeBitorderMsb);
    return fbBuilder.offset;
  }
  int addModeBitorderLsb(bool? modeBitorderLsb) {
    fbBuilder.addBool(3, modeBitorderLsb);
    return fbBuilder.offset;
  }
  int addPsuDisable(bool? psuDisable) {
    fbBuilder.addBool(4, psuDisable);
    return fbBuilder.offset;
  }
  int addPsuEnable(bool? psuEnable) {
    fbBuilder.addBool(5, psuEnable);
    return fbBuilder.offset;
  }
  int addPsuSetMv(int? psuSetMv) {
    fbBuilder.addUint32(6, psuSetMv);
    return fbBuilder.offset;
  }
  int addPsuSetMa(int? psuSetMa) {
    fbBuilder.addUint16(7, psuSetMa);
    return fbBuilder.offset;
  }
  int addPullupDisable(bool? pullupDisable) {
    fbBuilder.addBool(8, pullupDisable);
    return fbBuilder.offset;
  }
  int addPullupEnable(bool? pullupEnable) {
    fbBuilder.addBool(9, pullupEnable);
    return fbBuilder.offset;
  }
  int addPullxConfig(int? pullxConfig) {
    fbBuilder.addUint32(10, pullxConfig);
    return fbBuilder.offset;
  }
  int addIoDirectionMask(int? ioDirectionMask) {
    fbBuilder.addUint8(11, ioDirectionMask);
    return fbBuilder.offset;
  }
  int addIoDirection(int? ioDirection) {
    fbBuilder.addUint8(12, ioDirection);
    return fbBuilder.offset;
  }
  int addIoValueMask(int? ioValueMask) {
    fbBuilder.addUint8(13, ioValueMask);
    return fbBuilder.offset;
  }
  int addIoValue(int? ioValue) {
    fbBuilder.addUint8(14, ioValue);
    return fbBuilder.offset;
  }
  int addLedResume(bool? ledResume) {
    fbBuilder.addBool(15, ledResume);
    return fbBuilder.offset;
  }
  int addLedColorOffset(int? offset) {
    fbBuilder.addOffset(16, offset);
    return fbBuilder.offset;
  }
  int addPrintStringOffset(int? offset) {
    fbBuilder.addOffset(17, offset);
    return fbBuilder.offset;
  }
  int addHardwareBootloader(bool? hardwareBootloader) {
    fbBuilder.addBool(18, hardwareBootloader);
    return fbBuilder.offset;
  }
  int addHardwareReset(bool? hardwareReset) {
    fbBuilder.addBool(19, hardwareReset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ConfigurationRequestObjectBuilder extends fb.ObjectBuilder {
  final String? _mode;
  final ModeConfigurationObjectBuilder? _modeConfiguration;
  final bool? _modeBitorderMsb;
  final bool? _modeBitorderLsb;
  final bool? _psuDisable;
  final bool? _psuEnable;
  final int? _psuSetMv;
  final int? _psuSetMa;
  final bool? _pullupDisable;
  final bool? _pullupEnable;
  final int? _pullxConfig;
  final int? _ioDirectionMask;
  final int? _ioDirection;
  final int? _ioValueMask;
  final int? _ioValue;
  final bool? _ledResume;
  final List<int>? _ledColor;
  final String? _printString;
  final bool? _hardwareBootloader;
  final bool? _hardwareReset;

  ConfigurationRequestObjectBuilder({
    String? mode,
    ModeConfigurationObjectBuilder? modeConfiguration,
    bool? modeBitorderMsb,
    bool? modeBitorderLsb,
    bool? psuDisable,
    bool? psuEnable,
    int? psuSetMv,
    int? psuSetMa,
    bool? pullupDisable,
    bool? pullupEnable,
    int? pullxConfig,
    int? ioDirectionMask,
    int? ioDirection,
    int? ioValueMask,
    int? ioValue,
    bool? ledResume,
    List<int>? ledColor,
    String? printString,
    bool? hardwareBootloader,
    bool? hardwareReset,
  })
      : _mode = mode,
        _modeConfiguration = modeConfiguration,
        _modeBitorderMsb = modeBitorderMsb,
        _modeBitorderLsb = modeBitorderLsb,
        _psuDisable = psuDisable,
        _psuEnable = psuEnable,
        _psuSetMv = psuSetMv,
        _psuSetMa = psuSetMa,
        _pullupDisable = pullupDisable,
        _pullupEnable = pullupEnable,
        _pullxConfig = pullxConfig,
        _ioDirectionMask = ioDirectionMask,
        _ioDirection = ioDirection,
        _ioValueMask = ioValueMask,
        _ioValue = ioValue,
        _ledResume = ledResume,
        _ledColor = ledColor,
        _printString = printString,
        _hardwareBootloader = hardwareBootloader,
        _hardwareReset = hardwareReset;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? modeOffset = _mode == null ? null
        : fbBuilder.writeString(_mode!);
    final int? modeConfigurationOffset = _modeConfiguration?.getOrCreateOffset(fbBuilder);
    final int? ledColorOffset = _ledColor == null ? null
        : fbBuilder.writeListUint32(_ledColor!);
    final int? printStringOffset = _printString == null ? null
        : fbBuilder.writeString(_printString!);
    fbBuilder.startTable(20);
    fbBuilder.addOffset(0, modeOffset);
    fbBuilder.addOffset(1, modeConfigurationOffset);
    fbBuilder.addBool(2, _modeBitorderMsb);
    fbBuilder.addBool(3, _modeBitorderLsb);
    fbBuilder.addBool(4, _psuDisable);
    fbBuilder.addBool(5, _psuEnable);
    fbBuilder.addUint32(6, _psuSetMv);
    fbBuilder.addUint16(7, _psuSetMa);
    fbBuilder.addBool(8, _pullupDisable);
    fbBuilder.addBool(9, _pullupEnable);
    fbBuilder.addUint32(10, _pullxConfig);
    fbBuilder.addUint8(11, _ioDirectionMask);
    fbBuilder.addUint8(12, _ioDirection);
    fbBuilder.addUint8(13, _ioValueMask);
    fbBuilder.addUint8(14, _ioValue);
    fbBuilder.addBool(15, _ledResume);
    fbBuilder.addOffset(16, ledColorOffset);
    fbBuilder.addOffset(17, printStringOffset);
    fbBuilder.addBool(18, _hardwareBootloader);
    fbBuilder.addBool(19, _hardwareReset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ConfigurationResponse {
  ConfigurationResponse._(this._bc, this._bcOffset);
  factory ConfigurationResponse(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ConfigurationResponse> reader = _ConfigurationResponseReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get error => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'ConfigurationResponse{error: ${error}}';
  }
}

class _ConfigurationResponseReader extends fb.TableReader<ConfigurationResponse> {
  const _ConfigurationResponseReader();

  @override
  ConfigurationResponse createObject(fb.BufferContext bc, int offset) => 
    ConfigurationResponse._(bc, offset);
}

class ConfigurationResponseBuilder {
  ConfigurationResponseBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addErrorOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ConfigurationResponseObjectBuilder extends fb.ObjectBuilder {
  final String? _error;

  ConfigurationResponseObjectBuilder({
    String? error,
  })
      : _error = error;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? errorOffset = _error == null ? null
        : fbBuilder.writeString(_error!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, errorOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class DataRequest {
  DataRequest._(this._bc, this._bcOffset);
  factory DataRequest(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DataRequest> reader = _DataRequestReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  bool get startMain => const fb.BoolReader().vTableGet(_bc, _bcOffset, 4, false);
  bool get startAlt => const fb.BoolReader().vTableGet(_bc, _bcOffset, 6, false);
  List<int>? get dataWrite => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 8);
  int get bytesRead => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 10, 0);
  bool get stopMain => const fb.BoolReader().vTableGet(_bc, _bcOffset, 12, false);
  bool get stopAlt => const fb.BoolReader().vTableGet(_bc, _bcOffset, 14, false);

  @override
  String toString() {
    return 'DataRequest{startMain: ${startMain}, startAlt: ${startAlt}, dataWrite: ${dataWrite}, bytesRead: ${bytesRead}, stopMain: ${stopMain}, stopAlt: ${stopAlt}}';
  }
}

class _DataRequestReader extends fb.TableReader<DataRequest> {
  const _DataRequestReader();

  @override
  DataRequest createObject(fb.BufferContext bc, int offset) => 
    DataRequest._(bc, offset);
}

class DataRequestBuilder {
  DataRequestBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(6);
  }

  int addStartMain(bool? startMain) {
    fbBuilder.addBool(0, startMain);
    return fbBuilder.offset;
  }
  int addStartAlt(bool? startAlt) {
    fbBuilder.addBool(1, startAlt);
    return fbBuilder.offset;
  }
  int addDataWriteOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addBytesRead(int? bytesRead) {
    fbBuilder.addUint16(3, bytesRead);
    return fbBuilder.offset;
  }
  int addStopMain(bool? stopMain) {
    fbBuilder.addBool(4, stopMain);
    return fbBuilder.offset;
  }
  int addStopAlt(bool? stopAlt) {
    fbBuilder.addBool(5, stopAlt);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DataRequestObjectBuilder extends fb.ObjectBuilder {
  final bool? _startMain;
  final bool? _startAlt;
  final List<int>? _dataWrite;
  final int? _bytesRead;
  final bool? _stopMain;
  final bool? _stopAlt;

  DataRequestObjectBuilder({
    bool? startMain,
    bool? startAlt,
    List<int>? dataWrite,
    int? bytesRead,
    bool? stopMain,
    bool? stopAlt,
  })
      : _startMain = startMain,
        _startAlt = startAlt,
        _dataWrite = dataWrite,
        _bytesRead = bytesRead,
        _stopMain = stopMain,
        _stopAlt = stopAlt;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? dataWriteOffset = _dataWrite == null ? null
        : fbBuilder.writeListUint8(_dataWrite!);
    fbBuilder.startTable(6);
    fbBuilder.addBool(0, _startMain);
    fbBuilder.addBool(1, _startAlt);
    fbBuilder.addOffset(2, dataWriteOffset);
    fbBuilder.addUint16(3, _bytesRead);
    fbBuilder.addBool(4, _stopMain);
    fbBuilder.addBool(5, _stopAlt);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class DataResponse {
  DataResponse._(this._bc, this._bcOffset);
  factory DataResponse(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DataResponse> reader = _DataResponseReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get error => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  List<int>? get dataRead => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'DataResponse{error: ${error}, dataRead: ${dataRead}}';
  }
}

class _DataResponseReader extends fb.TableReader<DataResponse> {
  const _DataResponseReader();

  @override
  DataResponse createObject(fb.BufferContext bc, int offset) => 
    DataResponse._(bc, offset);
}

class DataResponseBuilder {
  DataResponseBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addErrorOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addDataReadOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DataResponseObjectBuilder extends fb.ObjectBuilder {
  final String? _error;
  final List<int>? _dataRead;

  DataResponseObjectBuilder({
    String? error,
    List<int>? dataRead,
  })
      : _error = error,
        _dataRead = dataRead;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? errorOffset = _error == null ? null
        : fbBuilder.writeString(_error!);
    final int? dataReadOffset = _dataRead == null ? null
        : fbBuilder.writeListUint8(_dataRead!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, errorOffset);
    fbBuilder.addOffset(1, dataReadOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class RequestPacket {
  RequestPacket._(this._bc, this._bcOffset);
  factory RequestPacket(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<RequestPacket> reader = _RequestPacketReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get versionMajor => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get versionMinor => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 6, 1);
  RequestPacketContentsTypeId? get contentsType => RequestPacketContentsTypeId._createOrNull(const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 8));
  dynamic get contents {
    switch (contentsType?.value) {
      case 1: return StatusRequest.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 2: return ConfigurationRequest.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 3: return DataRequest.reader.vTableGetNullable(_bc, _bcOffset, 10);
      default: return null;
    }
  }

  @override
  String toString() {
    return 'RequestPacket{versionMajor: ${versionMajor}, versionMinor: ${versionMinor}, contentsType: ${contentsType}, contents: ${contents}}';
  }
}

class _RequestPacketReader extends fb.TableReader<RequestPacket> {
  const _RequestPacketReader();

  @override
  RequestPacket createObject(fb.BufferContext bc, int offset) => 
    RequestPacket._(bc, offset);
}

class RequestPacketBuilder {
  RequestPacketBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addVersionMajor(int? versionMajor) {
    fbBuilder.addUint8(0, versionMajor);
    return fbBuilder.offset;
  }
  int addVersionMinor(int? versionMinor) {
    fbBuilder.addUint8(1, versionMinor);
    return fbBuilder.offset;
  }
  int addContentsType(RequestPacketContentsTypeId? contentsType) {
    fbBuilder.addUint8(2, contentsType?.value);
    return fbBuilder.offset;
  }
  int addContentsOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class RequestPacketObjectBuilder extends fb.ObjectBuilder {
  final int? _versionMajor;
  final int? _versionMinor;
  final RequestPacketContentsTypeId? _contentsType;
  final dynamic _contents;

  RequestPacketObjectBuilder({
    int? versionMajor,
    int? versionMinor,
    RequestPacketContentsTypeId? contentsType,
    dynamic contents,
  })
      : _versionMajor = versionMajor,
        _versionMinor = versionMinor,
        _contentsType = contentsType,
        _contents = contents;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? contentsOffset = _contents?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(4);
    fbBuilder.addUint8(0, _versionMajor);
    fbBuilder.addUint8(1, _versionMinor);
    fbBuilder.addUint8(2, _contentsType?.value);
    fbBuilder.addOffset(3, contentsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ErrorResponse {
  ErrorResponse._(this._bc, this._bcOffset);
  factory ErrorResponse(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ErrorResponse> reader = _ErrorResponseReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get error => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'ErrorResponse{error: ${error}}';
  }
}

class _ErrorResponseReader extends fb.TableReader<ErrorResponse> {
  const _ErrorResponseReader();

  @override
  ErrorResponse createObject(fb.BufferContext bc, int offset) => 
    ErrorResponse._(bc, offset);
}

class ErrorResponseBuilder {
  ErrorResponseBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addErrorOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ErrorResponseObjectBuilder extends fb.ObjectBuilder {
  final String? _error;

  ErrorResponseObjectBuilder({
    String? error,
  })
      : _error = error;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? errorOffset = _error == null ? null
        : fbBuilder.writeString(_error!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, errorOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ResponsePacket {
  ResponsePacket._(this._bc, this._bcOffset);
  factory ResponsePacket(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ResponsePacket> reader = _ResponsePacketReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get versionMajor => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get versionMinor => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 6, 1);
  ResponsePacketContentsTypeId? get contentsType => ResponsePacketContentsTypeId._createOrNull(const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 8));
  dynamic get contents {
    switch (contentsType?.value) {
      case 1: return ErrorResponse.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 2: return StatusResponse.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 3: return ConfigurationResponse.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 4: return DataResponse.reader.vTableGetNullable(_bc, _bcOffset, 10);
      default: return null;
    }
  }

  @override
  String toString() {
    return 'ResponsePacket{versionMajor: ${versionMajor}, versionMinor: ${versionMinor}, contentsType: ${contentsType}, contents: ${contents}}';
  }
}

class _ResponsePacketReader extends fb.TableReader<ResponsePacket> {
  const _ResponsePacketReader();

  @override
  ResponsePacket createObject(fb.BufferContext bc, int offset) => 
    ResponsePacket._(bc, offset);
}

class ResponsePacketBuilder {
  ResponsePacketBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addVersionMajor(int? versionMajor) {
    fbBuilder.addUint8(0, versionMajor);
    return fbBuilder.offset;
  }
  int addVersionMinor(int? versionMinor) {
    fbBuilder.addUint8(1, versionMinor);
    return fbBuilder.offset;
  }
  int addContentsType(ResponsePacketContentsTypeId? contentsType) {
    fbBuilder.addUint8(2, contentsType?.value);
    return fbBuilder.offset;
  }
  int addContentsOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ResponsePacketObjectBuilder extends fb.ObjectBuilder {
  final int? _versionMajor;
  final int? _versionMinor;
  final ResponsePacketContentsTypeId? _contentsType;
  final dynamic _contents;

  ResponsePacketObjectBuilder({
    int? versionMajor,
    int? versionMinor,
    ResponsePacketContentsTypeId? contentsType,
    dynamic contents,
  })
      : _versionMajor = versionMajor,
        _versionMinor = versionMinor,
        _contentsType = contentsType,
        _contents = contents;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? contentsOffset = _contents?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(4);
    fbBuilder.addUint8(0, _versionMajor);
    fbBuilder.addUint8(1, _versionMinor);
    fbBuilder.addUint8(2, _contentsType?.value);
    fbBuilder.addOffset(3, contentsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
