# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpio

class RequestPacketContents(object):
    NONE = 0
    Monster = 1
    StatusRequest = 2
    ConfigurationRequest = 3
    DataRequest = 4
