// automatically generated by the FlatBuffers compiler, do not modify

package bpio

@Suppress("unused")
class Color private constructor() {
    companion object {
        const val Red: Byte = 0
        const val Green: Byte = 1
        const val Blue: Byte = 2
    }
}
