<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace bpio;

class RequestPacketContents
{
    const NONE = 0;
    const Monster = 1;
    const StatusRequest = 2;
    const ConfigurationRequest = 3;
    const DataRequest = 4;

    private static $names = array(
        RequestPacketContents::NONE=>"NONE",
        RequestPacketContents::Monster=>"Monster",
        RequestPacketContents::StatusRequest=>"StatusRequest",
        RequestPacketContents::ConfigurationRequest=>"ConfigurationRequest",
        RequestPacketContents::DataRequest=>"DataRequest",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
