<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace bpio;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class RequestPacket extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return RequestPacket
     */
    public static function getRootAsRequestPacket(ByteBuffer $bb)
    {
        $obj = new RequestPacket();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return RequestPacket
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return byte
     */
    public function getVersionMajor()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return byte
     */
    public function getVersionMinor()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 1;
    }

    /**
     * @return byte
     */
    public function getContentsType()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : \bpio\RequestPacketContents::NONE;
    }

    /**
     * @returnint
     */
    public function getContents($obj)
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->__union($obj, $o) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startRequestPacket(FlatBufferBuilder $builder)
    {
        $builder->StartObject(4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return RequestPacket
     */
    public static function createRequestPacket(FlatBufferBuilder $builder, $version_major, $version_minor, $contents_type, $contents)
    {
        $builder->startObject(4);
        self::addVersionMajor($builder, $version_major);
        self::addVersionMinor($builder, $version_minor);
        self::addContentsType($builder, $contents_type);
        self::addContents($builder, $contents);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addVersionMajor(FlatBufferBuilder $builder, $versionMajor)
    {
        $builder->addByteX(0, $versionMajor, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addVersionMinor(FlatBufferBuilder $builder, $versionMinor)
    {
        $builder->addByteX(1, $versionMinor, 1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addContentsType(FlatBufferBuilder $builder, $contentsType)
    {
        $builder->addByteX(2, $contentsType, 0);
    }

    public static function addContents(FlatBufferBuilder $builder, $offset)
    {
        $builder->addOffsetX(3, $offset, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endRequestPacket(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
