<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace bpio;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class ResponsePacket extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ResponsePacket
     */
    public static function getRootAsResponsePacket(ByteBuffer $bb)
    {
        $obj = new ResponsePacket();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ResponsePacket
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getError()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return byte
     */
    public function getContentsType()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : \bpio\ResponsePacketContents::NONE;
    }

    /**
     * @returnint
     */
    public function getContents($obj)
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__union($obj, $o) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startResponsePacket(FlatBufferBuilder $builder)
    {
        $builder->StartObject(3);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return ResponsePacket
     */
    public static function createResponsePacket(FlatBufferBuilder $builder, $error, $contents_type, $contents)
    {
        $builder->startObject(3);
        self::addError($builder, $error);
        self::addContentsType($builder, $contents_type);
        self::addContents($builder, $contents);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addError(FlatBufferBuilder $builder, $error)
    {
        $builder->addOffsetX(0, $error, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addContentsType(FlatBufferBuilder $builder, $contentsType)
    {
        $builder->addByteX(1, $contentsType, 0);
    }

    public static function addContents(FlatBufferBuilder $builder, $offset)
    {
        $builder->addOffsetX(2, $offset, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endResponsePacket(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }

    public static function finishResponsePacketBuffer(FlatBufferBuilder $builder, $offset)
    {
        $builder->finish($offset);
    }
}
