<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace bpio;

class ResponsePacketContents
{
    const NONE = 0;
    const StatusResponse = 1;
    const ConfigurationResponse = 2;
    const DataResponse = 3;

    private static $names = array(
        ResponsePacketContents::NONE=>"NONE",
        ResponsePacketContents::StatusResponse=>"StatusResponse",
        ResponsePacketContents::ConfigurationResponse=>"ConfigurationResponse",
        ResponsePacketContents::DataResponse=>"DataResponse",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
