<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace bpio;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class StatusResponse extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return StatusResponse
     */
    public static function getRootAsStatusResponse(ByteBuffer $bb)
    {
        $obj = new StatusResponse();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return StatusResponse
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getError()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return byte
     */
    public function getVersionHardwareMajor()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return byte
     */
    public function getVersionHardwareMinor()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return byte
     */
    public function getVersionFirmwareMajor()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return byte
     */
    public function getVersionFirmwareMinor()
    {
        $o = $this->__offset(12);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    public function getVersionFirmwareGitHash()
    {
        $o = $this->__offset(14);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getVersionFirmwareDate()
    {
        $o = $this->__offset(16);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param int offset
     * @return string
     */
    public function getModesAvailable($j)
    {
        $o = $this->__offset(18);
        return $o != 0 ? $this->__string($this->__vector($o) + $j * 4) : 0;
    }

    /**
     * @return int
     */
    public function getModesAvailableLength()
    {
        $o = $this->__offset(18);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    public function getModeCurrent()
    {
        $o = $this->__offset(20);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param int offset
     * @return string
     */
    public function getModePinLabels($j)
    {
        $o = $this->__offset(22);
        return $o != 0 ? $this->__string($this->__vector($o) + $j * 4) : 0;
    }

    /**
     * @return int
     */
    public function getModePinLabelsLength()
    {
        $o = $this->__offset(22);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @return bool
     */
    public function getModeBitorderMsb()
    {
        $o = $this->__offset(24);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return uint
     */
    public function getModeMaxPacketSize()
    {
        $o = $this->__offset(26);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : 0;
    }

    /**
     * @return uint
     */
    public function getModeMaxWrite()
    {
        $o = $this->__offset(28);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : 0;
    }

    /**
     * @return uint
     */
    public function getModeMaxRead()
    {
        $o = $this->__offset(30);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : 0;
    }

    /**
     * @return bool
     */
    public function getPsuEnabled()
    {
        $o = $this->__offset(32);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return uint
     */
    public function getPsuSetMv()
    {
        $o = $this->__offset(34);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : 0;
    }

    /**
     * @return uint
     */
    public function getPsuSetMa()
    {
        $o = $this->__offset(36);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : 0;
    }

    /**
     * @return uint
     */
    public function getPsuMeasuredMv()
    {
        $o = $this->__offset(38);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : 0;
    }

    /**
     * @return uint
     */
    public function getPsuMeasuredMa()
    {
        $o = $this->__offset(40);
        return $o != 0 ? $this->bb->getUint($o + $this->bb_pos) : 0;
    }

    /**
     * @return bool
     */
    public function getPsuCurrentError()
    {
        $o = $this->__offset(42);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @return bool
     */
    public function getPullupEnabled()
    {
        $o = $this->__offset(44);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @param int offset
     * @return uint
     */
    public function getAdcMv($j)
    {
        $o = $this->__offset(46);
        return $o != 0 ? $this->bb->getUint($this->__vector($o) + $j * 4) : 0;
    }

    /**
     * @return int
     */
    public function getAdcMvLength()
    {
        $o = $this->__offset(46);
        return $o != 0 ? $this->__vector_len($o) : 0;
    }

    /**
     * @return byte
     */
    public function getIoDirection()
    {
        $o = $this->__offset(48);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return byte
     */
    public function getIoValue()
    {
        $o = $this->__offset(50);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @return float
     */
    public function getDiskSizeMb()
    {
        $o = $this->__offset(52);
        return $o != 0 ? $this->bb->getFloat($o + $this->bb_pos) : 0.0;
    }

    /**
     * @return float
     */
    public function getDiskUsedMb()
    {
        $o = $this->__offset(54);
        return $o != 0 ? $this->bb->getFloat($o + $this->bb_pos) : 0.0;
    }

    /**
     * @return byte
     */
    public function getLedCount()
    {
        $o = $this->__offset(56);
        return $o != 0 ? $this->bb->getByte($o + $this->bb_pos) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startStatusResponse(FlatBufferBuilder $builder)
    {
        $builder->StartObject(27);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return StatusResponse
     */
    public static function createStatusResponse(FlatBufferBuilder $builder, $error, $version_hardware_major, $version_hardware_minor, $version_firmware_major, $version_firmware_minor, $version_firmware_git_hash, $version_firmware_date, $modes_available, $mode_current, $mode_pin_labels, $mode_bitorder_msb, $mode_max_packet_size, $mode_max_write, $mode_max_read, $psu_enabled, $psu_set_mv, $psu_set_ma, $psu_measured_mv, $psu_measured_ma, $psu_current_error, $pullup_enabled, $adc_mv, $io_direction, $io_value, $disk_size_mb, $disk_used_mb, $led_count)
    {
        $builder->startObject(27);
        self::addError($builder, $error);
        self::addVersionHardwareMajor($builder, $version_hardware_major);
        self::addVersionHardwareMinor($builder, $version_hardware_minor);
        self::addVersionFirmwareMajor($builder, $version_firmware_major);
        self::addVersionFirmwareMinor($builder, $version_firmware_minor);
        self::addVersionFirmwareGitHash($builder, $version_firmware_git_hash);
        self::addVersionFirmwareDate($builder, $version_firmware_date);
        self::addModesAvailable($builder, $modes_available);
        self::addModeCurrent($builder, $mode_current);
        self::addModePinLabels($builder, $mode_pin_labels);
        self::addModeBitorderMsb($builder, $mode_bitorder_msb);
        self::addModeMaxPacketSize($builder, $mode_max_packet_size);
        self::addModeMaxWrite($builder, $mode_max_write);
        self::addModeMaxRead($builder, $mode_max_read);
        self::addPsuEnabled($builder, $psu_enabled);
        self::addPsuSetMv($builder, $psu_set_mv);
        self::addPsuSetMa($builder, $psu_set_ma);
        self::addPsuMeasuredMv($builder, $psu_measured_mv);
        self::addPsuMeasuredMa($builder, $psu_measured_ma);
        self::addPsuCurrentError($builder, $psu_current_error);
        self::addPullupEnabled($builder, $pullup_enabled);
        self::addAdcMv($builder, $adc_mv);
        self::addIoDirection($builder, $io_direction);
        self::addIoValue($builder, $io_value);
        self::addDiskSizeMb($builder, $disk_size_mb);
        self::addDiskUsedMb($builder, $disk_used_mb);
        self::addLedCount($builder, $led_count);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addError(FlatBufferBuilder $builder, $error)
    {
        $builder->addOffsetX(0, $error, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addVersionHardwareMajor(FlatBufferBuilder $builder, $versionHardwareMajor)
    {
        $builder->addByteX(1, $versionHardwareMajor, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addVersionHardwareMinor(FlatBufferBuilder $builder, $versionHardwareMinor)
    {
        $builder->addByteX(2, $versionHardwareMinor, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addVersionFirmwareMajor(FlatBufferBuilder $builder, $versionFirmwareMajor)
    {
        $builder->addByteX(3, $versionFirmwareMajor, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addVersionFirmwareMinor(FlatBufferBuilder $builder, $versionFirmwareMinor)
    {
        $builder->addByteX(4, $versionFirmwareMinor, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addVersionFirmwareGitHash(FlatBufferBuilder $builder, $versionFirmwareGitHash)
    {
        $builder->addOffsetX(5, $versionFirmwareGitHash, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addVersionFirmwareDate(FlatBufferBuilder $builder, $versionFirmwareDate)
    {
        $builder->addOffsetX(6, $versionFirmwareDate, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addModesAvailable(FlatBufferBuilder $builder, $modesAvailable)
    {
        $builder->addOffsetX(7, $modesAvailable, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createModesAvailableVector(FlatBufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putOffset($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startModesAvailableVector(FlatBufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addModeCurrent(FlatBufferBuilder $builder, $modeCurrent)
    {
        $builder->addOffsetX(8, $modeCurrent, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addModePinLabels(FlatBufferBuilder $builder, $modePinLabels)
    {
        $builder->addOffsetX(9, $modePinLabels, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createModePinLabelsVector(FlatBufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putOffset($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startModePinLabelsVector(FlatBufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addModeBitorderMsb(FlatBufferBuilder $builder, $modeBitorderMsb)
    {
        $builder->addBoolX(10, $modeBitorderMsb, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addModeMaxPacketSize(FlatBufferBuilder $builder, $modeMaxPacketSize)
    {
        $builder->addUintX(11, $modeMaxPacketSize, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addModeMaxWrite(FlatBufferBuilder $builder, $modeMaxWrite)
    {
        $builder->addUintX(12, $modeMaxWrite, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addModeMaxRead(FlatBufferBuilder $builder, $modeMaxRead)
    {
        $builder->addUintX(13, $modeMaxRead, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addPsuEnabled(FlatBufferBuilder $builder, $psuEnabled)
    {
        $builder->addBoolX(14, $psuEnabled, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addPsuSetMv(FlatBufferBuilder $builder, $psuSetMv)
    {
        $builder->addUintX(15, $psuSetMv, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addPsuSetMa(FlatBufferBuilder $builder, $psuSetMa)
    {
        $builder->addUintX(16, $psuSetMa, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addPsuMeasuredMv(FlatBufferBuilder $builder, $psuMeasuredMv)
    {
        $builder->addUintX(17, $psuMeasuredMv, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param uint
     * @return void
     */
    public static function addPsuMeasuredMa(FlatBufferBuilder $builder, $psuMeasuredMa)
    {
        $builder->addUintX(18, $psuMeasuredMa, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addPsuCurrentError(FlatBufferBuilder $builder, $psuCurrentError)
    {
        $builder->addBoolX(19, $psuCurrentError, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addPullupEnabled(FlatBufferBuilder $builder, $pullupEnabled)
    {
        $builder->addBoolX(20, $pullupEnabled, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param VectorOffset
     * @return void
     */
    public static function addAdcMv(FlatBufferBuilder $builder, $adcMv)
    {
        $builder->addOffsetX(21, $adcMv, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param array offset array
     * @return int vector offset
     */
    public static function createAdcMvVector(FlatBufferBuilder $builder, array $data)
    {
        $builder->startVector(4, count($data), 4);
        for ($i = count($data) - 1; $i >= 0; $i--) {
            $builder->putUint($data[$i]);
        }
        return $builder->endVector();
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int $numElems
     * @return void
     */
    public static function startAdcMvVector(FlatBufferBuilder $builder, $numElems)
    {
        $builder->startVector(4, $numElems, 4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addIoDirection(FlatBufferBuilder $builder, $ioDirection)
    {
        $builder->addByteX(22, $ioDirection, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addIoValue(FlatBufferBuilder $builder, $ioValue)
    {
        $builder->addByteX(23, $ioValue, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param float
     * @return void
     */
    public static function addDiskSizeMb(FlatBufferBuilder $builder, $diskSizeMb)
    {
        $builder->addFloatX(24, $diskSizeMb, 0.0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param float
     * @return void
     */
    public static function addDiskUsedMb(FlatBufferBuilder $builder, $diskUsedMb)
    {
        $builder->addFloatX(25, $diskUsedMb, 0.0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param byte
     * @return void
     */
    public static function addLedCount(FlatBufferBuilder $builder, $ledCount)
    {
        $builder->addByteX(26, $ledCount, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endStatusResponse(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
