// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace bpio
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ConfigurationResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ConfigurationResponse GetRootAsConfigurationResponse(ByteBuffer _bb) { return GetRootAsConfigurationResponse(_bb, new ConfigurationResponse()); }
  public static ConfigurationResponse GetRootAsConfigurationResponse(ByteBuffer _bb, ConfigurationResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ConfigurationResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Error { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetErrorBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetErrorArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<bpio.ConfigurationResponse> CreateConfigurationResponse(FlatBufferBuilder builder,
      StringOffset errorOffset = default(StringOffset)) {
    builder.StartTable(1);
    ConfigurationResponse.AddError(builder, errorOffset);
    return ConfigurationResponse.EndConfigurationResponse(builder);
  }

  public static void StartConfigurationResponse(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddError(FlatBufferBuilder builder, StringOffset errorOffset) { builder.AddOffset(0, errorOffset.Value, 0); }
  public static Offset<bpio.ConfigurationResponse> EndConfigurationResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<bpio.ConfigurationResponse>(o);
  }
}


static public class ConfigurationResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Error*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
