// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace bpio
{

public enum RequestPacketContents : byte
{
  NONE = 0,
  StatusRequest = 1,
  ConfigurationRequest = 2,
  DataRequest = 3,
};



static public class RequestPacketContentsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((RequestPacketContents)typeId)
    {
      case RequestPacketContents.StatusRequest:
        result = bpio.StatusRequestVerify.Verify(verifier, tablePos);
        break;
      case RequestPacketContents.ConfigurationRequest:
        result = bpio.ConfigurationRequestVerify.Verify(verifier, tablePos);
        break;
      case RequestPacketContents.DataRequest:
        result = bpio.DataRequestVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
