// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace bpio
{

public enum ResponsePacketContents : byte
{
  NONE = 0,
  StatusResponse = 1,
  ConfigurationResponse = 2,
  DataResponse = 3,
};



static public class ResponsePacketContentsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((ResponsePacketContents)typeId)
    {
      case ResponsePacketContents.StatusResponse:
        result = bpio.StatusResponseVerify.Verify(verifier, tablePos);
        break;
      case ResponsePacketContents.ConfigurationResponse:
        result = bpio.ConfigurationResponseVerify.Verify(verifier, tablePos);
        break;
      case ResponsePacketContents.DataResponse:
        result = bpio.DataResponseVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
