// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace bpio
{

public enum StatusRequestTypes : sbyte
{
  All = 0,
  Version = 1,
  Mode = 2,
  Pullup = 3,
  PSU = 4,
  ADC = 5,
  IO = 6,
  Disk = 7,
  LED = 8,
};


}
