// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bpio

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConfigurationResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsConfigurationResponse(buf []byte, offset flatbuffers.UOffsetT) *ConfigurationResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConfigurationResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishConfigurationResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConfigurationResponse(buf []byte, offset flatbuffers.UOffsetT) *ConfigurationResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConfigurationResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConfigurationResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConfigurationResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConfigurationResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConfigurationResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConfigurationResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ConfigurationResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(error), 0)
}
func ConfigurationResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
