// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bpio

import "strconv"

type RequestPacketContents byte

const (
	RequestPacketContentsNONE                 RequestPacketContents = 0
	RequestPacketContentsStatusRequest        RequestPacketContents = 1
	RequestPacketContentsConfigurationRequest RequestPacketContents = 2
	RequestPacketContentsDataRequest          RequestPacketContents = 3
)

var EnumNamesRequestPacketContents = map[RequestPacketContents]string{
	RequestPacketContentsNONE:                 "NONE",
	RequestPacketContentsStatusRequest:        "StatusRequest",
	RequestPacketContentsConfigurationRequest: "ConfigurationRequest",
	RequestPacketContentsDataRequest:          "DataRequest",
}

var EnumValuesRequestPacketContents = map[string]RequestPacketContents{
	"NONE":                 RequestPacketContentsNONE,
	"StatusRequest":        RequestPacketContentsStatusRequest,
	"ConfigurationRequest": RequestPacketContentsConfigurationRequest,
	"DataRequest":          RequestPacketContentsDataRequest,
}

func (v RequestPacketContents) String() string {
	if s, ok := EnumNamesRequestPacketContents[v]; ok {
		return s
	}
	return "RequestPacketContents(" + strconv.FormatInt(int64(v), 10) + ")"
}
