// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bpio

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResponsePacket struct {
	_tab flatbuffers.Table
}

func GetRootAsResponsePacket(buf []byte, offset flatbuffers.UOffsetT) *ResponsePacket {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResponsePacket{}
	x.Init(buf, n+offset)
	return x
}

func FinishResponsePacketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsResponsePacket(buf []byte, offset flatbuffers.UOffsetT) *ResponsePacket {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ResponsePacket{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedResponsePacketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ResponsePacket) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResponsePacket) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResponsePacket) VersionMajor() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 2
}

func (rcv *ResponsePacket) MutateVersionMajor(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *ResponsePacket) VersionMinor() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ResponsePacket) MutateVersionMinor(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *ResponsePacket) ContentsType() ResponsePacketContents {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return ResponsePacketContents(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ResponsePacket) MutateContentsType(n ResponsePacketContents) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *ResponsePacket) Contents(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func ResponsePacketStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ResponsePacketAddVersionMajor(builder *flatbuffers.Builder, versionMajor byte) {
	builder.PrependByteSlot(0, versionMajor, 2)
}
func ResponsePacketAddVersionMinor(builder *flatbuffers.Builder, versionMinor byte) {
	builder.PrependByteSlot(1, versionMinor, 0)
}
func ResponsePacketAddContentsType(builder *flatbuffers.Builder, contentsType ResponsePacketContents) {
	builder.PrependByteSlot(2, byte(contentsType), 0)
}
func ResponsePacketAddContents(builder *flatbuffers.Builder, contents flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(contents), 0)
}
func ResponsePacketEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
