// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bpio

import "strconv"

type ResponsePacketContents byte

const (
	ResponsePacketContentsNONE                  ResponsePacketContents = 0
	ResponsePacketContentsStatusResponse        ResponsePacketContents = 1
	ResponsePacketContentsConfigurationResponse ResponsePacketContents = 2
	ResponsePacketContentsDataResponse          ResponsePacketContents = 3
)

var EnumNamesResponsePacketContents = map[ResponsePacketContents]string{
	ResponsePacketContentsNONE:                  "NONE",
	ResponsePacketContentsStatusResponse:        "StatusResponse",
	ResponsePacketContentsConfigurationResponse: "ConfigurationResponse",
	ResponsePacketContentsDataResponse:          "DataResponse",
}

var EnumValuesResponsePacketContents = map[string]ResponsePacketContents{
	"NONE":                  ResponsePacketContentsNONE,
	"StatusResponse":        ResponsePacketContentsStatusResponse,
	"ConfigurationResponse": ResponsePacketContentsConfigurationResponse,
	"DataResponse":          ResponsePacketContentsDataResponse,
}

func (v ResponsePacketContents) String() string {
	if s, ok := EnumNamesResponsePacketContents[v]; ok {
		return s
	}
	return "ResponsePacketContents(" + strconv.FormatInt(int64(v), 10) + ")"
}
