// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bpio

import "strconv"

type StatusRequestTypes int8

const (
	StatusRequestTypesAll     StatusRequestTypes = 0
	StatusRequestTypesVersion StatusRequestTypes = 1
	StatusRequestTypesMode    StatusRequestTypes = 2
	StatusRequestTypesPullup  StatusRequestTypes = 3
	StatusRequestTypesPSU     StatusRequestTypes = 4
	StatusRequestTypesADC     StatusRequestTypes = 5
	StatusRequestTypesIO      StatusRequestTypes = 6
	StatusRequestTypesDisk    StatusRequestTypes = 7
	StatusRequestTypesLED     StatusRequestTypes = 8
)

var EnumNamesStatusRequestTypes = map[StatusRequestTypes]string{
	StatusRequestTypesAll:     "All",
	StatusRequestTypesVersion: "Version",
	StatusRequestTypesMode:    "Mode",
	StatusRequestTypesPullup:  "Pullup",
	StatusRequestTypesPSU:     "PSU",
	StatusRequestTypesADC:     "ADC",
	StatusRequestTypesIO:      "IO",
	StatusRequestTypesDisk:    "Disk",
	StatusRequestTypesLED:     "LED",
}

var EnumValuesStatusRequestTypes = map[string]StatusRequestTypes{
	"All":     StatusRequestTypesAll,
	"Version": StatusRequestTypesVersion,
	"Mode":    StatusRequestTypesMode,
	"Pullup":  StatusRequestTypesPullup,
	"PSU":     StatusRequestTypesPSU,
	"ADC":     StatusRequestTypesADC,
	"IO":      StatusRequestTypesIO,
	"Disk":    StatusRequestTypesDisk,
	"LED":     StatusRequestTypesLED,
}

func (v StatusRequestTypes) String() string {
	if s, ok := EnumNamesStatusRequestTypes[v]; ok {
		return s
	}
	return "StatusRequestTypes(" + strconv.FormatInt(int64(v), 10) + ")"
}
