// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bpio

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StatusResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *StatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatusResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatusResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *StatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatusResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatusResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatusResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatusResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatusResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StatusResponse) HardwareVersionMajor() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutateHardwareVersionMajor(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *StatusResponse) HardwareVersionMinor() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutateHardwareVersionMinor(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *StatusResponse) FirmwareVersionMajor() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutateFirmwareVersionMajor(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

func (rcv *StatusResponse) FirmwareVersionMinor() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutateFirmwareVersionMinor(n byte) bool {
	return rcv._tab.MutateByteSlot(12, n)
}

func (rcv *StatusResponse) FirmwareGitHash() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StatusResponse) FirmwareDate() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StatusResponse) ModesAvailable(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *StatusResponse) ModesAvailableLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StatusResponse) ModeCurrent() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StatusResponse) ModePinLabels(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *StatusResponse) ModePinLabelsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StatusResponse) ModeBitorderMsb() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StatusResponse) MutateModeBitorderMsb(n bool) bool {
	return rcv._tab.MutateBoolSlot(24, n)
}

func (rcv *StatusResponse) PsuEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StatusResponse) MutatePsuEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func (rcv *StatusResponse) PsuSetMv() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutatePsuSetMv(n uint32) bool {
	return rcv._tab.MutateUint32Slot(28, n)
}

func (rcv *StatusResponse) PsuSetMa() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutatePsuSetMa(n uint32) bool {
	return rcv._tab.MutateUint32Slot(30, n)
}

func (rcv *StatusResponse) PsuMeasuredMv() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutatePsuMeasuredMv(n uint32) bool {
	return rcv._tab.MutateUint32Slot(32, n)
}

func (rcv *StatusResponse) PsuMeasuredMa() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutatePsuMeasuredMa(n uint32) bool {
	return rcv._tab.MutateUint32Slot(34, n)
}

func (rcv *StatusResponse) PsuCurrentError() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StatusResponse) MutatePsuCurrentError(n bool) bool {
	return rcv._tab.MutateBoolSlot(36, n)
}

func (rcv *StatusResponse) PullupEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StatusResponse) MutatePullupEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(38, n)
}

func (rcv *StatusResponse) PullxConfig() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutatePullxConfig(n uint32) bool {
	return rcv._tab.MutateUint32Slot(40, n)
}

func (rcv *StatusResponse) AdcMv(j int) uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *StatusResponse) AdcMvLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StatusResponse) MutateAdcMv(j int, n uint32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *StatusResponse) IoDirection() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutateIoDirection(n byte) bool {
	return rcv._tab.MutateByteSlot(44, n)
}

func (rcv *StatusResponse) IoValue() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutateIoValue(n byte) bool {
	return rcv._tab.MutateByteSlot(46, n)
}

func (rcv *StatusResponse) DiskSizeMb() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(48))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StatusResponse) MutateDiskSizeMb(n float32) bool {
	return rcv._tab.MutateFloat32Slot(48, n)
}

func (rcv *StatusResponse) DiskUsedMb() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(50))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StatusResponse) MutateDiskUsedMb(n float32) bool {
	return rcv._tab.MutateFloat32Slot(50, n)
}

func (rcv *StatusResponse) LedCount() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(52))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusResponse) MutateLedCount(n byte) bool {
	return rcv._tab.MutateByteSlot(52, n)
}

func StatusResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(25)
}
func StatusResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(error), 0)
}
func StatusResponseAddHardwareVersionMajor(builder *flatbuffers.Builder, hardwareVersionMajor byte) {
	builder.PrependByteSlot(1, hardwareVersionMajor, 0)
}
func StatusResponseAddHardwareVersionMinor(builder *flatbuffers.Builder, hardwareVersionMinor byte) {
	builder.PrependByteSlot(2, hardwareVersionMinor, 0)
}
func StatusResponseAddFirmwareVersionMajor(builder *flatbuffers.Builder, firmwareVersionMajor byte) {
	builder.PrependByteSlot(3, firmwareVersionMajor, 0)
}
func StatusResponseAddFirmwareVersionMinor(builder *flatbuffers.Builder, firmwareVersionMinor byte) {
	builder.PrependByteSlot(4, firmwareVersionMinor, 0)
}
func StatusResponseAddFirmwareGitHash(builder *flatbuffers.Builder, firmwareGitHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(firmwareGitHash), 0)
}
func StatusResponseAddFirmwareDate(builder *flatbuffers.Builder, firmwareDate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(firmwareDate), 0)
}
func StatusResponseAddModesAvailable(builder *flatbuffers.Builder, modesAvailable flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(modesAvailable), 0)
}
func StatusResponseStartModesAvailableVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StatusResponseAddModeCurrent(builder *flatbuffers.Builder, modeCurrent flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(modeCurrent), 0)
}
func StatusResponseAddModePinLabels(builder *flatbuffers.Builder, modePinLabels flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(modePinLabels), 0)
}
func StatusResponseStartModePinLabelsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StatusResponseAddModeBitorderMsb(builder *flatbuffers.Builder, modeBitorderMsb bool) {
	builder.PrependBoolSlot(10, modeBitorderMsb, false)
}
func StatusResponseAddPsuEnabled(builder *flatbuffers.Builder, psuEnabled bool) {
	builder.PrependBoolSlot(11, psuEnabled, false)
}
func StatusResponseAddPsuSetMv(builder *flatbuffers.Builder, psuSetMv uint32) {
	builder.PrependUint32Slot(12, psuSetMv, 0)
}
func StatusResponseAddPsuSetMa(builder *flatbuffers.Builder, psuSetMa uint32) {
	builder.PrependUint32Slot(13, psuSetMa, 0)
}
func StatusResponseAddPsuMeasuredMv(builder *flatbuffers.Builder, psuMeasuredMv uint32) {
	builder.PrependUint32Slot(14, psuMeasuredMv, 0)
}
func StatusResponseAddPsuMeasuredMa(builder *flatbuffers.Builder, psuMeasuredMa uint32) {
	builder.PrependUint32Slot(15, psuMeasuredMa, 0)
}
func StatusResponseAddPsuCurrentError(builder *flatbuffers.Builder, psuCurrentError bool) {
	builder.PrependBoolSlot(16, psuCurrentError, false)
}
func StatusResponseAddPullupEnabled(builder *flatbuffers.Builder, pullupEnabled bool) {
	builder.PrependBoolSlot(17, pullupEnabled, false)
}
func StatusResponseAddPullxConfig(builder *flatbuffers.Builder, pullxConfig uint32) {
	builder.PrependUint32Slot(18, pullxConfig, 0)
}
func StatusResponseAddAdcMv(builder *flatbuffers.Builder, adcMv flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(19, flatbuffers.UOffsetT(adcMv), 0)
}
func StatusResponseStartAdcMvVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StatusResponseAddIoDirection(builder *flatbuffers.Builder, ioDirection byte) {
	builder.PrependByteSlot(20, ioDirection, 0)
}
func StatusResponseAddIoValue(builder *flatbuffers.Builder, ioValue byte) {
	builder.PrependByteSlot(21, ioValue, 0)
}
func StatusResponseAddDiskSizeMb(builder *flatbuffers.Builder, diskSizeMb float32) {
	builder.PrependFloat32Slot(22, diskSizeMb, 0.0)
}
func StatusResponseAddDiskUsedMb(builder *flatbuffers.Builder, diskUsedMb float32) {
	builder.PrependFloat32Slot(23, diskUsedMb, 0.0)
}
func StatusResponseAddLedCount(builder *flatbuffers.Builder, ledCount byte) {
	builder.PrependByteSlot(24, ledCount, 0)
}
func StatusResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
